# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias sfd='sudo fastboot devices'
alias sffb='sudo fastboot flash boot boot.img'
alias sffsext4='sudo fastboot flash system system.img.ext4'
alias sffs='sudo fastboot flash system system.img'
alias sffs512='sudo fastboot -S 512M flash system system.img'
alias sff='sudo fastboot flash'
alias sfr='sudo fastboot reboot'
alias aslk='aslk'

alias ffb='fastboot flash boot boot.img'
alias ffs='fastboot flash system system.img'
alias ffsext4='fastboot flash system system.img.ext4'
alias ff='fastboot flash'
alias fr='fastboot reboot'
alias sshmount40='sudo sshfs -o cache=yes,allow_other qiancheng@172.21.1.40:/home/qiancheng ~/sshfs_mount'
alias sshmount27='sshfs -o cache=yes qiancheng@172.21.1.27:/home/qiancheng ~/sshfs_mount'
alias ssshmount27='sudo sshfs -o cache=yes qiancheng@172.21.1.27:/home/qiancheng ~/ssshfs_mount'
alias sshmount143='sudo sshfs -o cache=yes,allow_other qiancheng@172.21.1.143:/home/qiancheng ~/sshfs_mount'
alias sshmount151='sshfs -o cache=yes liuyang@172.21.1.151:/work/liuyang/ ~/qmyfile'
alias adbrb='adb reboot-bootloader'
alias adbd='adb devices'
alias ard='adb reboot edl'
alias d='cd ..'
alias f='find . -name'
alias zhuomian='~/桌面'
alias xiazai='~/下载'
alias zm='~/桌面'
alias xz='~/下载'
alias cdx='cd ~/下载'
alias cdz='cd ~/桌面'
alias cdw='cd ~/文档'
alias ssh27='ssh -l qiancheng 172.21.1.27'
alias mini921600='minicom -b 921600'

alias kmsg='while true; do adb shell cat /proc/kmsg; sleep 0.5; done'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

JAVA_HOME=/usr/java/jdk1.6.0_34
PATH=$PATH:$JAVA_HOME/bin:/home/q/tool:~/android-studio/bin
CLASSPATH=.:$JAVA_HOME/lib
export JAVA_HOME
export PATH
export CLASSPATH

export XZ=~/下载
export ZM=~/桌面

# GRADLE_HOME是Gradle的所在目录
# GRADLE_HOME=/opt/gradle-2.0
# export GRADLE_HOME
export HEXAGON_ROOT=~/Qualcomm/HEXAGON_Tools
